### ISSUE TITLE
5p layout not correctly rendered when table is added

### ISSUE THREAD

**Issue by SHolm3s** [quarto-journals/elsevier#24]
Hi, I am using the elsevier quarto extension for a paper I am writing.  When I add a markdown table, the 5p format is not rendering correctly. It is fine without the table, but with the table, some of the text in the beginning is cut off. 

This is the render from the template file :
![image](https://github.com/quarto-journals/elsevier/assets/88152029/eea4e8f5-8867-4e4c-81e6-b6bc29ff2a86)

Now when I just replace the content under the heading "Tables coming from R" with my own markdown table, I get this render:
![image](https://github.com/quarto-journals/elsevier/assets/88152029/fe3f601f-41b7-4555-b1f1-e2b7d50c8a3f)

Everything above "Using CSL" is cut off! Could you help see why this is happening?

**Comment by SHolm3s** [comment]
Thanks for the suggestion! I will see if I see it in the latex file and report back

**Comment by SHolm3s** [comment]
Hi, I checked the latex file, and the code that you mentioned is present in the generated latex. The top part is still cut off though

**Comment by dragonstyle** [comment]
Can you share the latex (or see whether the table in the document is a ‘longtable’)?

**Comment by SHolm3s** [comment]
I am attaching the latex file. I think I saw "longtable" at the end, 
[longtable_cuts_off_text.txt](https://github.com/quarto-journals/elsevier/files/14845830/longtable_cuts_off_text.txt)

Thanks a lot for taking the time to help!

**Comment by dragonstyle** [comment]
Yeah it definitely seems like everything should be working, but it sure looks like the table is evading our special handling. I'll need to try to drill into the LaTeX more carefully to diagnose what is happening...

**Comment by cscheid** [comment]
Can you provide a `.qmd` file that causes this as well as the latex file?

**Comment by SHolm3s** [comment]
I actually am using quarto from jupyterlab and rendering the .ipynb file. But I made a qmd file too just now. The problem persists. I am attaching the qmd code in txt file
[elsevier5p_tablecutoff_qmd.txt](https://github.com/quarto-journals/elsevier/files/14856008/elsevier5p_tablecutoff_qmd.txt)

**Comment by SHolm3s** [comment]
Hi, Any luck with the debugging process ? Also I wanted to ask an unrelated question. Is there any way to span a figure across the 2 columns in 5p or 3p ?

**Comment by MitchellAcoustics** [comment]
> Hi, Any luck with the debugging process ? Also I wanted to ask an unrelated question. Is there any way to span a figure across the 2 columns in 5p or 3p ?

Quarto provides the way to do this with figures with `fig-env="figure*"` [https://quarto.org/docs/authoring/figures.html#environments](https://quarto.org/docs/authoring/figures.html#environments)

Some examples from a document I'm working on:

```md
![Steps for calculating the SPI.](figures/SPI-framework.drawio.png){#fig-bespoke-spi width="100%" fig-env="figure*"}
```

It's not documented, but I got it to work with embedded figures by wrapping it in the fenced div.
```md
::: {#fig-targets fig-env="figure*"}
{{< embed notebooks/SingleIndex-Code.ipynb#fig-targets >}}
:::
```

I haven't figured out how to get a table to span both columns though - that's what brought me to this issue! @dragonstyle is this possible with longtable? 

In another two-column latex template I use, it can be done be done with `table*` in latex just like the figure environment, but quarto hasn't incorporated a table environment option yet.

**Comment by haiiliin** [comment]
I found a solution that replaces `longtable` environment with `tabular` environment, which makes the placement of tables quite flexible:

```tex
\usepackage{booktabs}

\def\tcaption{Please redefine table caption and label before the table definition using \texttt{\textbackslash tcaption\{Table caption\}} and \texttt{\textbackslash tlabel\{tbl-label\}}.}
\def\tlabel{tbl-label}

\def\longtable{
    \begin{$if(table.env)$$table.env$$else$table$endif$}[$if(table.pos)$$table.pos$$else$!htb$endif$]
    \caption{\tcaption}
    \label{\tlabel}
    \renewcommand{\caption}[1]{}
    \renewcommand{\label}[1]{}
    \tabular
}
\def\endlongtable{
    \bottomrule
    \endtabular
    \end{$if(table.env)$$table.env$$else$table$endif$}
}
\let\tabularnewline\relax
\let\endfirsthead\iffalse
\let\endlastfoot\fi

```
